# Generated by Django 3.2.7 on 2022-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_clientemodel_clientedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='productoSubTipo',
            field=models.CharField(db_column='productoSubTipo', default='kfc', max_length=10),
        ),
        migrations.AddField(
            model_name='productomodel',
            name='productoTipo',
            field=models.CharField(choices=[('1', 'comidaRapida'), ('2', 'miniMarket'), ('3', 'supermercado')], db_column='productoTipo', default='1', max_length=10),
        ),
    ]
