# Generated by Django 3.2.7 on 2022-07-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_clientemodel_clientetipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteTipo',
            field=models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'MIEMBRO'), (3, 'CLIENTE')], db_column='tipo', default=3, null=True),
        ),
    ]
