# Generated by Django 3.2.7 on 2022-08-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_clientemodel_clientetipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='clienteDireccion',
            field=models.CharField(db_column='direccion', max_length=50, null=True, verbose_name='Dirección del usuario'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteCelular',
            field=models.IntegerField(db_column='celular', null=True),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDocumento',
            field=models.CharField(db_column='documento', max_length=9),
        ),
    ]
