# Generated by Django 3.2.7 on 2022-08-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20220801_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='clienteDocumento',
            field=models.CharField(db_column='documento', max_length=9, null=True),
        ),
    ]
