# Generated by Django 4.0.4 on 2022-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productos_stockproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='ejemplo',
            field=models.CharField(default='hola', max_length=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stockProducto',
            field=models.CharField(max_length=20),
        ),
    ]
