# Generated by Django 4.0.4 on 2022-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productos_ejemplo_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
