# Generated by Django 4.0.4 on 2022-06-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='clienteTipo',
            field=models.CharField(choices=[(1, 'embutidos'), (2, 'a'), (3, 'b')], default='1', max_length=10),
        ),
    ]
