# Generated by Django 4.0.4 on 2022-07-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_productos_clientetipo_productos_productotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='productoTipo',
            field=models.CharField(choices=[('1', 'comidaRapida'), ('2', 'miniMarket'), ('3', 'supermercado')], max_length=10),
        ),
    ]
