# Generated by Django 4.0.4 on 2022-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_productos_productotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='productoSubTipo',
            field=models.CharField(default='pollo', max_length=10),
        ),
    ]
