# Generated by Django 4.0.4 on 2022-07-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productos_productosubtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='productoSubTipo',
            field=models.CharField(max_length=10),
        ),
    ]
